---
roles:
  - name: samdoran.fish
    version: 1.3.1
  - name: geerlingguy.docker
    version: 4.1.0
  - name: geerlingguy.security
    version: 2.0.1
  - name: geerlingguy.firewall
    version: 2.5.0
  - name: geerlingguy.ntp
    version: 2.3.0
  - src: https://github.com/adamcharnock/ansible-netplan
    version: master
    name: adamcharnock.netplan
collections:
  - name: ansible.posix
    version: 1.3.0
